# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: minifinancier.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("minifinancier.proto", :syntax => :proto3) do
    add_message "minifinancier.ChargeRequest" do
      optional :user_id, :uint64, 1
      optional :amount, :uint32, 2
    end
    add_message "minifinancier.Payment" do
      optional :id, :string, 1
      optional :user_id, :uint64, 2
      optional :amount, :uint32, 3
      optional :create_time, :message, 4, "google.protobuf.Timestamp"
    end
  end
end

module Minifinancier
  ChargeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("minifinancier.ChargeRequest").msgclass
  Payment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("minifinancier.Payment").msgclass
end
