source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.4'
# Use mysql as the database for Active Record
gem 'mysql2', '~> 0.5'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

gem 'graphql'
gem 'graphql_playground-rails'
gem 'grpc'
gem 'ridgepole', require: false
gem 'unicorn'
gem 'revision_plate'
gem 'rack-cors'
gem 'rack-timeout'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]

  gem 'rubocop', require: false
end

group :development do
  gem 'listen', '~> 3.3'

  gem 'grpc-tools', require: false
  gem 'unicorn-rails'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
